---
services:
  database:
    image: postgres:16
    environment:
      TZ: Europe/Berlin
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "5432:5432/tcp"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'rkKB84SG2NOYITcxMkSeFw=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    ports:
      - "29092:29092/tcp"
      - "9092:9092/tcp"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_started
    environment:
      TZ: Europe/Berlin
      KAFKA_CLUSTERS_0_NAME: bluebird-play
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8081:8080/tcp"

  symbiote:
    image: symbiote:latest
    depends_on:
      kafka:
        condition: service_started
      database:
        condition: service_healthy
    environment:
      TZ: Europe/Berlin
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bluebird
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
      ORG_BLUEBIRD_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      ORG_BLUEBIRD_KAFKA_INTEGRATION_OPENNMS_GROUPID: opennms
      ORG_BLUEBIRD_KAFKA_INTEGRATION_OPENNMS_TOPICS_EVENTS: events
      ORG_BLUEBIRD_KAFKA_INTEGRATION_OPENNMS_TOPICS_ALARMS: alarms
      ORG_BLUEBIRD_KAFKA_INTEGRATION_OPENNMS_TOPICS_NODES: nodes
      ORG_BLUEBIRD_INTEGRATION_OPENNMS_HOME: /opennms
    volumes:
      - "./opennms:/opennms"
    ports:
      - "8080:8080/tcp"
