---
name: symbiote-build
run-name: Build and run test suites
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/java-builder:0.0.1.jdk-21
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build from source
        run: |
          make build
      - name: Run tests
        run: |
          make tests
      - name: Persist build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eventbus-jar
          path: target/eventbus-*.jar
      - name: Login to Quay registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push container image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/labmonkeys/symbiote
